export const loudlyMoods = [
    "Dreamy",
    "Laid Back",
    "Dark",
    "Hopeful",
    "Happy",
    "Cool",
    "Dadda",
    "Energetic",
    "Fun",
    "Intense",
    "Upbeat",
    "Exotic",
    "Flowing",
    "Groovy",
    "Carefree",
    "Euphoric",
    "Crazy"
] as const;

export type LoudlyMood = typeof loudlyMoods[number];

export const loudlyGenres = [
    "Funk",
    "Beats",
    "Indian",
    "Folk & Singer-Songwriter",
    "Arabic",
    "Country",
    "Ambient",
    "Dubstep",
    "Classic Rock",
    "EDM",
    "Classical",
    "Alternative Rock",
    "Hip-hop & Rap",
    "House",
    "Electronic",
    "Drum & Bass",
    "Grime",
    "Afrobeat",
    "Indie",
    "Jazz/Blues",
    "J-pop",
    "Latin",
    "Lounge",
    "Metal",
    "Cinematic",
    "Pop",
    "Punk",
    "Reggae/Dub",
    "Soul/R&B",
    "Synthwave",
    "Techno",
    "Trance",
    "Trap",
    "World",
    "Boom-bap",
    "Gangsta Rap ",
    "Conscious Rap ",
    "Crunk ",
    "East-Coast ",
    "West-Coast ",
    "Lo-Fi Hip Hop ",
    "Chillhop ",
    "Cloud Rap ",
    "Mumble Rap ",
    "Drill ",
    "Emo Rap ",
    "Old School ",
    "Liquid ",
    "Jungle ",
    "Garage ",
    "2-Step ",
    "Bassmusic ",
    "Speed Garage ",
    "Bachata ",
    "Tango SUB",
    "Merengue ",
    "Reggaeton ",
    "Salsa ",
    "Cumbia ",
    "Bossa Nova ",
    "Samba ",
    "Vallenato ",
    "Bolero ",
    "Breakbeat ",
    "Big Beat ",
    "Brostep ",
    "Chillstep ",
    "Electro House ",
    "Trance SUB",
    "Acid Trance ",
    "Deep House ",
    "Electroswing ",
    "Acid House ",
    "Future House ",
    "Chicago House ",
    "French House ",
    "Funky House ",
    "G House ",
    "Italo disco ",
    "Progressive House ",
    "Tech House ",
    "Afro House ",
    "Ambient House ",
    "Disco ",
    "Gabber ",
    "Hardcore ",
    "Hardstyle ",
    "Minimal ",
    "Acid Techno ",
    "Detroit Techno ",
    "Goa ",
    "Psytrance ",
    "Americana ",
    "Bluegrass  ",
    "Folk Rock ",
    "Indie Dance ",
    "Indie Pop ",
    "Electro ",
    "Electronica ",
    "Acid Jazz ",
    "Balearic Beat ",
    "Chill Out ",
    "Moombahton ",
    "Trip Hop ",
    "Glitch Hop ",
    "Future Bass ",
    "Art Punk ",
    "Emo ",
    "Goth ",
    "Grunge ",
    "Lo-Fi ",
    "Prog Rock ",
    "New Wave ",
    "Post Punk ",
    "Industrial ",
    "Britpop ",
    "Rockabilly ",
    "Shoegaze ",
    "Math Rock ",
    "Yacht Rock ",
    "Synthpop ",
    "Moombathon"
] as const;

export const getCorrespondingLoudlyGenre = (genre: string): LoudlyGenre|undefined => {
    const lc = genre.toLocaleLowerCase();
    const result = loudlyGenres.find(g => g.toLocaleLowerCase() === lc);
    return result;
}

export type LoudlyGenre = typeof loudlyGenres[number];

export const loudlyKeys = [
    "Ab/G# Major",
    "Ab/G# Minor",
    "A Major",
    "A Minor",
    "Bb/A# Major",
    "Bb/A# Minor",
    "B Major",
    "B Minor",
    "C Major",
    "C Minor",
    "Db/C# Minor",
    "D Major",
    "D Minor",
    "Eb/D# Major",
    "Eb/D# Minor",
    "E Major",
    "E Minor",
    "F Major",
    "F Minor",
    "Gb/F# Major",
    "Gb/F# Minor",
    "G Major",
    "G Minor"
] as const;

export type LoudlyKey = typeof loudlyKeys[number];