import Head from 'next/head'

const Home = () => <>
	<Head>
		<title>Plml Shows</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/favicon.ico" />
	</Head>
	<main className="">
		Hello world
	</main>
</>

export default Home;