export const musicCategories = [
    "Joie",
    "Tristesse",
    "Excitation",
    "Mélancolie",
    "Enthousiasme",
    "Calme",
    "Émerveillement",
    "Amour",
    "Colère",
    "Paix intérieure",
    "Espoir",
    "Frustration",
    "Sérénité",
    "Nostalgie",
    "Surprise",
    "Admiration",
    "Confusion",
    "Energie",
    "Rêverie",
    "Gratitude",
    "Rage",
    "Contemplative",
    "Beats",
    "Epique"
]